"use client";
import Link from "next/link"; import { useEffect, useMemo, useState } from "react"; import type { Trip } from "@/app/lib/trips"; import { useSchedules } from "@/app/lib/use-schedules"; import { useTransports } from "@/app/lib/use-transports"; import { useReservations } from "@/app/lib/use-reservations"; import { useRecords } from "@/app/lib/use-records"; import { getTripDates } from "@/app/lib/trip-summary"; import { TRANSPORT_MODE_LABELS } from "@/app/lib/transports"; import { summarizeMainTravelCosts } from "@/app/lib/travel-costs";
export default function PlanFlow({ trip, onActiveDateChange }: { trip: Trip; onActiveDateChange?: (date: string) => void }) {
  const { schedules } = useSchedules(trip.id), { transports } = useTransports(trip.id), { reservations } = useReservations(trip.id), { records } = useRecords(trip.id);
  const populated = useMemo(() => getTripDates(trip.startDate, trip.endDate).filter((date) => schedules.some((item) => item.date === date) || transports.some((item) => item.departureDate === date) || reservations.some((item) => item.startAt.slice(0, 10) === date)), [trip, schedules, transports, reservations]);
  const [selected, setSelected] = useState(""); const active = selected && populated.includes(selected) ? selected : populated[0] ?? trip.startDate;
  useEffect(() => onActiveDateChange?.(active), [active, onActiveDateChange]);
  const items = useMemo(() => [...schedules.filter((item) => item.date === active).map((item) => ({ id: `s-${item.id}`, time: item.startTime, label: "予定", title: item.title, detail: item.place })), ...transports.filter((item) => item.departureDate === active).map((item) => ({ id: `t-${item.id}`, time: item.departureTime, label: "移動", title: `${item.departurePlace} → ${item.arrivalPlace}`, detail: `${TRANSPORT_MODE_LABELS[item.mode]} ${item.serviceName}` })), ...reservations.filter((item) => item.startAt.slice(0, 10) === active).map((item) => ({ id: `r-${item.id}`, time: item.startAt.slice(11, 16), label: "予約", title: item.name, detail: item.type }))].sort((a, b) => a.time.localeCompare(b.time)), [active, schedules, transports, reservations]);
  const costs = useMemo(() => summarizeMainTravelCosts(reservations, transports, records), [reservations, transports, records]);
  return <section className="mt-5 rounded-2xl bg-white p-4 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-bold text-teal-700">TRIP FLOW</p><h2 className="mt-1 text-xl font-bold">日別の旅行計画</h2></div><div className="text-right"><p className="text-xs text-stone-500">主な旅行費用・登録分</p><p className="font-bold tabular-nums">{yen(costs.total)}</p></div></div><details className="mt-3 rounded-xl bg-stone-50 px-3"><summary className="flex min-h-12 cursor-pointer items-center text-sm font-bold text-teal-800">概算の内訳を見る</summary><dl className="grid gap-3 border-t border-stone-200 py-4 text-sm sm:grid-cols-3"><Cost label="予約金額" value={costs.reservationAmount} /><Cost label="移動運賃" value={costs.transportFare} /><Cost label="その他の費用" value={costs.otherExpenses} /></dl></details>{!populated.length ? <div className="py-8 text-center"><p className="text-sm text-stone-500">予定や移動はまだありません。</p><div className="mt-3 flex justify-center gap-4"><Link href={`/trips/${trip.id}/schedule/new`} className="inline-flex min-h-12 items-center font-bold text-teal-800">予定を追加</Link><Link href={`/trips/${trip.id}/transports/new`} className="inline-flex min-h-12 items-center font-bold text-teal-800">移動を追加</Link></div></div> : <><div role="tablist" aria-label="計画日" className="-mx-4 mt-4 flex gap-2 overflow-x-auto px-4 pb-2 sm:mx-0 sm:px-0">{populated.map((date) => <button key={date} role="tab" aria-selected={date === active} onClick={() => setSelected(date)} className={`min-h-12 shrink-0 rounded-full px-4 text-sm font-bold ${date === active ? "bg-teal-700 text-white" : "bg-stone-100 text-stone-600"}`}>{dayNumber(trip.startDate, date)}日目</button>)}</div><ol className="mt-3 divide-y divide-stone-100">{items.map((item) => <li key={item.id} className="grid grid-cols-[3.5rem_1fr] gap-3 py-4"><time className="text-sm tabular-nums text-stone-500">{item.time || "--:--"}</time><div className="min-w-0"><p className="text-xs font-bold text-teal-700">{item.label}</p><p className="mt-0.5 break-words font-bold">{item.title}</p>{item.detail && <p className="mt-1 break-words text-sm text-stone-500">{item.detail}</p>}</div></li>)}</ol></>}</section>;
}
function Cost({ label, value }: { label: string; value: number }) { return <div className="flex justify-between gap-3 sm:block"><dt className="text-stone-500">{label}</dt><dd className="font-bold tabular-nums sm:mt-1">{yen(value)}</dd></div>; }
function dayNumber(start: string, date: string) { return Math.round((new Date(`${date}T00:00`).getTime() - new Date(`${start}T00:00`).getTime()) / 86400000) + 1; } function yen(value: number) { return `${new Intl.NumberFormat("ja-JP").format(value)}円`; }
