"use client";
import { useRouter } from "next/navigation";
import { useRef, useState, type FormEvent } from "react";
import { createTransportId, deleteTransport, findPreviousTransport, saveTransport, TRANSPORT_MODES, TRANSPORT_MODE_LABELS, updateTransport, validateTransportValues, type Transport, type TransportMode, type TransportValues } from "@/app/lib/transports";
import type { Trip } from "@/app/lib/trips";
import { FormActions, FormField, inputClass } from "@/app/components/ui";
import { useTransports } from "@/app/lib/use-transports";

export type TransportPrefill = Partial<TransportValues>;
export default function TransportForm({ trip, transport, prefill = {} }: { trip: Trip; transport?: Transport; prefill?: TransportPrefill }) {
  const router = useRouter(); const [mode, setMode] = useState<TransportMode>(transport?.mode ?? prefill.mode ?? "shinkansen"); const [errors, setErrors] = useState<ReturnType<typeof validateTransportValues> & { storage?: string }>({}); const [saving, setSaving] = useState(false); const lock = useRef(false); const back = `/trips/${trip.id}`;
  const { transports } = useTransports(trip.id); const [departureDate, setDepartureDate] = useState(transport?.departureDate ?? prefill.departureDate ?? trip.startDate); const [departureTime, setDepartureTime] = useState(transport?.departureTime ?? prefill.departureTime ?? ""); const [manualDeparture, setManualDeparture] = useState<string | null>(transport?.departurePlace ?? prefill.departurePlace ?? null); const previous = transport ? undefined : findPreviousTransport(transports, departureDate, departureTime); const departurePlace = manualDeparture ?? previous?.arrivalPlace ?? ""; const suggestedDeparture = manualDeparture === null && Boolean(previous?.arrivalPlace);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (lock.current) return; const d = new FormData(event.currentTarget); const text = (name: string) => String(d.get(name) ?? "").trim(); const values: TransportValues = { mode, departurePlace: text("departurePlace"), arrivalPlace: text("arrivalPlace"), departureDate: text("departureDate"), departureTime: text("departureTime"), arrivalDate: text("arrivalDate"), arrivalTime: text("arrivalTime"), serviceName: text("serviceName"), operator: text("operator"), departurePlatform: text("departurePlatform"), arrivalPlatform: text("arrivalPlatform"), terminal: text("terminal"), carNumber: text("carNumber"), seatNumber: text("seatNumber"), fare: text("fare"), bookingUrl: text("bookingUrl"), memo: text("memo"), reservationId: transport?.reservationId ?? prefill.reservationId ?? "" }; const found = validateTransportValues(values, trip.startDate, trip.endDate); if (Object.keys(found).length) { setErrors(found); return; } lock.current = true; setSaving(true); const now = new Date().toISOString(); const item: Transport = { ...values, id: transport?.id ?? createTransportId(), tripId: trip.id, arrivalDate: values.arrivalDate || (values.arrivalTime ? values.departureDate : ""), fare: values.fare === "" ? null : Number(values.fare), createdAt: transport?.createdAt ?? now, updatedAt: now }; try { if (transport) updateTransport(transport.id, item); else saveTransport(item); router.push(back); } catch { lock.current = false; setSaving(false); setErrors({ storage: "移動を保存できませんでした。入力内容は維持されています。" }); } }
  function remove() { if (transport && confirm(`「${transport.departurePlace} → ${transport.arrivalPlace}」を削除しますか？`)) { deleteTransport(transport.id); router.push(back); } }
  const value = (key: keyof TransportValues, fallback = "") => String(transport?.[key as keyof Transport] ?? prefill[key] ?? fallback);
  return <form onSubmit={submit} noValidate className="space-y-6 pt-6">{errors.storage && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{errors.storage}</p>}<div className="grid gap-6 sm:grid-cols-2">
    <FormField label="移動手段" required error={errors.mode} htmlFor="mode"><select id="mode" value={mode} onChange={(e) => setMode(e.target.value as TransportMode)} className={inputClass}>{TRANSPORT_MODES.map((x) => <option key={x} value={x}>{TRANSPORT_MODE_LABELS[x]}</option>)}</select></FormField>
    <div className="hidden sm:block" /><FormField label="出発地" required error={errors.departurePlace} htmlFor="departurePlace"><input id="departurePlace" name="departurePlace" value={departurePlace} onChange={(event) => setManualDeparture(event.target.value)} className={inputClass} />{suggestedDeparture && <p className="mt-1 text-xs text-stone-500">前の移動の到着地から入力しました</p>}</FormField><FormField label="到着地" required error={errors.arrivalPlace} htmlFor="arrivalPlace"><input id="arrivalPlace" name="arrivalPlace" defaultValue={value("arrivalPlace")} className={inputClass} /></FormField>
    <FormField label="出発日" required error={errors.departureDate} htmlFor="departureDate"><input id="departureDate" name="departureDate" type="date" min={trip.startDate} max={trip.endDate} value={departureDate} onChange={(event) => setDepartureDate(event.target.value)} className={inputClass} /></FormField><FormField label="出発時刻" required error={errors.departureTime} htmlFor="departureTime"><input id="departureTime" name="departureTime" type="time" value={departureTime} onChange={(event) => setDepartureTime(event.target.value)} className={inputClass} /></FormField>
    <FormField label="到着日" error={errors.arrivalDate} htmlFor="arrivalDate"><input id="arrivalDate" name="arrivalDate" type="date" min={trip.startDate} max={trip.endDate} defaultValue={value("arrivalDate")} className={inputClass} /></FormField><FormField label="到着時刻" error={errors.arrivalTime} htmlFor="arrivalTime"><input id="arrivalTime" name="arrivalTime" type="time" defaultValue={value("arrivalTime")} className={inputClass} /></FormField>
    <FormField label={serviceLabel(mode)} htmlFor="serviceName"><input id="serviceName" name="serviceName" defaultValue={value("serviceName")} className={inputClass} /></FormField><FormField label={operatorLabel(mode)} htmlFor="operator"><input id="operator" name="operator" defaultValue={value("operator")} className={inputClass} /></FormField>
    <FormField label={platformLabel(mode, true)} htmlFor="departurePlatform"><input id="departurePlatform" name="departurePlatform" defaultValue={value("departurePlatform")} className={inputClass} /></FormField><FormField label={platformLabel(mode, false)} htmlFor="arrivalPlatform"><input id="arrivalPlatform" name="arrivalPlatform" defaultValue={value("arrivalPlatform")} className={inputClass} /></FormField>
    <FormField label="ターミナル／営業所" htmlFor="terminal"><input id="terminal" name="terminal" defaultValue={value("terminal")} className={inputClass} /></FormField><FormField label={mode === "ferry" ? "客室" : "号車"} htmlFor="carNumber"><input id="carNumber" name="carNumber" defaultValue={value("carNumber")} className={inputClass} /></FormField><FormField label="座席" htmlFor="seatNumber"><input id="seatNumber" name="seatNumber" defaultValue={value("seatNumber")} className={inputClass} /></FormField><FormField label="運賃（支出には加算されません）" error={errors.fare} htmlFor="fare"><input id="fare" name="fare" type="number" inputMode="numeric" min="0" defaultValue={value("fare")} className={inputClass} /></FormField><FormField label="予約URL" error={errors.bookingUrl} htmlFor="bookingUrl"><input id="bookingUrl" name="bookingUrl" type="url" defaultValue={value("bookingUrl")} className={inputClass} /></FormField>
  </div><FormField label="メモ" htmlFor="memo"><textarea id="memo" name="memo" rows={4} defaultValue={value("memo")} className={`${inputClass} resize-y`} /></FormField><FormActions cancelHref={back} submitting={saving} submitLabel={transport ? "変更を保存" : "移動を保存"} />{transport && <button type="button" onClick={remove} className="inline-flex min-h-12 items-center text-sm text-stone-500 hover:text-red-700">この移動を削除</button>}</form>;
}
function serviceLabel(mode: TransportMode) { if (["local-train", "subway", "tram"].includes(mode)) return "路線名・行き先"; if (mode === "airplane") return "便名"; if (mode === "ferry") return "船名・便名"; if (mode === "rental-car") return "営業所名"; return "列車名・便名・バス名"; }
function operatorLabel(mode: TransportMode) { return mode === "airplane" ? "航空会社" : mode === "bus" || mode === "highway-bus" ? "バス会社" : "運行会社"; }
function platformLabel(mode: TransportMode, departure: boolean) { if (mode === "airplane") return departure ? "出発ターミナル" : "到着ターミナル"; if (["bus", "highway-bus", "ferry"].includes(mode)) return departure ? "乗り場" : "降り場"; if (mode === "rental-car") return departure ? "受取場所" : "返却場所"; return departure ? "出発ホーム" : "到着ホーム"; }
