import Link from "next/link";
import type { ReactNode } from "react";

export const inputClass = "mt-2 min-h-12 w-full rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-base text-stone-900 outline-none placeholder:text-stone-400 focus:border-teal-700 focus:ring-2 focus:ring-teal-700/20";
export const primaryButtonClass = "inline-flex min-h-12 items-center justify-center rounded-xl bg-teal-700 px-5 text-sm font-bold text-white transition hover:bg-teal-800 disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700";
export const secondaryButtonClass = "inline-flex min-h-12 items-center justify-center rounded-xl bg-stone-100 px-4 text-sm font-bold text-stone-800 transition hover:bg-stone-200 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700";

export function AppCard({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`rounded-2xl bg-white p-4 sm:p-5 ${className}`}>{children}</div>; }
export function SectionHeader({ id, title, count, href, actionLabel = "詳細入力" }: { id: string; title: string; count?: number; href?: string; actionLabel?: string }) { return <div className="flex min-h-12 items-center justify-between gap-4"><div className="flex min-w-0 items-baseline gap-2"><h2 id={id} className="text-lg font-bold tracking-tight">{title}</h2>{count !== undefined && <span className="text-xs font-medium text-stone-400">{count}件</span>}</div>{href && <Link href={href} className="inline-flex min-h-12 shrink-0 items-center text-sm font-bold text-teal-700 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-700">{actionLabel}</Link>}</div>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="py-8 text-center"><p className="font-bold text-stone-700">{title}</p>{description && <p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-stone-500">{description}</p>}{action && <div className="mt-4">{action}</div>}</div>; }
export function StatusBadge({ children, className = "" }: { children: ReactNode; className?: string }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${className}`}>{children}</span>; }
export function FormField({ label, required = false, error, htmlFor, children }: { label: string; required?: boolean; error?: string; htmlFor: string; children: ReactNode }) { return <div><label htmlFor={htmlFor} className="text-sm font-bold text-stone-800">{label}<span className={`ml-2 text-xs font-normal ${required ? "text-red-700" : "text-stone-400"}`}>{required ? "必須" : "任意"}</span></label>{children}{error && <p id={`${htmlFor}-error`} role="alert" className="mt-1.5 text-sm text-red-700">{error}</p>}</div>; }
export function FormActions({ cancelHref, submitting, submitLabel }: { cancelHref: string; submitting: boolean; submitLabel: string }) { return <div className="sticky bottom-[calc(5rem+env(safe-area-inset-bottom))] z-20 -mx-4 flex gap-3 border-t border-stone-200 bg-stone-50/95 px-4 py-3 backdrop-blur sm:static sm:mx-0 sm:justify-end sm:border-0 sm:bg-transparent sm:px-0 sm:pb-0"><Link href={cancelHref} className={`${secondaryButtonClass} min-h-14 flex-1 sm:min-h-12 sm:flex-none`}>キャンセル</Link><button type="submit" disabled={submitting} aria-busy={submitting} className={`${primaryButtonClass} min-h-14 flex-[2] sm:min-h-12 sm:flex-none`}>{submitting ? "保存中…" : submitLabel}</button></div>; }
